"""Regenerate tools_mcp/MANIFEST.md from tools_mcp/doctor.py's live report.

See the MCP wiring design notes: this supersedes hand-
editing MANIFEST.md -- a generated record can't drift from reality the
way a manually updated one can. doctor.py is authoritative; this file is
a convenience index only.

Usage:
    tools-env/.venv/bin/python -m tools_mcp.generate_manifest
"""

from __future__ import annotations

from pathlib import Path

from tools_mcp.doctor import EXTERNAL_SERVERS, REPO_ROOT, build_report

# Which stdio server each binary belongs to, for the manifest table --
# purely presentational; doctor.py's own checks don't need this grouping.
_SERVER_OF_BINARY = {
    "nmap": "recon",
    "gobuster": "recon",
    "dirb": "recon",
    "whois": "recon",
    "dig": "recon",
    "subfinder": "recon",
    "httpx": "recon",
    "tshark": "recon",
    "sqlmap": "webapp",
    "nuclei": "webapp",
    "arjun": "webapp",
    "searchsploit": "webapp",
    "dalfox": "webapp",
    "commix": "webapp",
    "ffuf": "webapp",
    "hydra": "webapp",
    "nikto": "webapp",
    "wpscan": "webapp",
    "npx": "blockchain",
    "forge": "blockchain",
    "slither": "blockchain",
    "echidna": "blockchain",
    "myth": "blockchain",
    "sol2uml": "blockchain",
}

_NOTES = {
    "hydra": "brute-force -- use with care, gated behind require_authorized_bruteforce",
    "dirb": "not packaged for macOS via Homebrew -- see install_command",
    "nuclei": "templates go stale independently -- see UPDATE_COMMANDS",
    "searchsploit": "exploit-db goes stale independently -- see UPDATE_COMMANDS",
    "wpscan": "vuln database goes stale independently -- see UPDATE_COMMANDS",
    "npx": "Hardhat runs project-local via npx --no-install; requires a checked-out in-scope repo",
    "forge": "Foundry tests/fuzzing operate on a checked-out in-scope repo",
    "echidna": "fuzzing requires ALLOW_FUZZING=true",
}


def render(report: dict) -> str:
    lines = [
        "# MCP tool server manifest",
        "",
        "Generated by `tools_mcp/generate_manifest.py` from `tools_mcp/doctor.py`'s",
        "live report -- do not hand-edit; re-run the generator instead. `doctor.py`",
        "is authoritative, this file is a convenience index only.",
        "",
        "| Server | Kind | Tool | Installed? | Notes |",
        "|---|---|---|---|---|",
    ]
    for binary, server in _SERVER_OF_BINARY.items():
        result = report["binaries"][binary]
        installed = "yes" if result["installed"] else "no"
        note = _NOTES.get(binary, "")
        lines.append(f"| {server} | stdio | {binary} | {installed} | {note} |")
    seclists = report["seclists"]
    lines.append(
        f"| recon/webapp | data | seclists | {'yes' if seclists['ok'] else 'no'} | "
        "wordlists for gobuster/dirb/ffuf -- goes stale independently, see UPDATE_COMMANDS |"
    )
    msf = report["metasploit"]
    lines.append(
        f"| metasploit | stdio | metasploit | {'yes' if msf['ok'] else 'no'} | "
        "official msfmcpd, self-starts its own RPC daemon -- read-only in v1 |"
    )
    for name in EXTERNAL_SERVERS:
        result = report["external_servers"][name]
        installed = "yes (reachable now)" if result["ok"] else "unknown -- app not open right now"
        note = "requires the GUI app open with its extension loaded"
        lines.append(f"| {name} | external | {name} | {installed} | {note} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    report = build_report()
    manifest_path = REPO_ROOT / "tools_mcp" / "MANIFEST.md"
    manifest_path.write_text(render(report))
    print(f"wrote {manifest_path}")


if __name__ == "__main__":
    main()
